async-http:
  url: https://github.com/socketry/async-http.git
  command: bundle exec rspec
async-websocket:
  url: https://github.com/socketry/async-websocket.git
  command: bundle exec sus
falcon:
  url: https://github.com/socketry/falcon.git
  command: bundle exec rspec
async-rest:
  url: https://github.com/socketry/async-rest.git
  command: bundle exec sus
